### PR TITLE
Add summary of the 29th meetup

### PR DESCRIPTION
**Pull request by ramonh**
Short and sweet :smile:

### CODE REVIEW

**Comment by alicetragedy** [comment]
this is awesome, thanks! I will merge later and change the date to tomorrow (or Friday) so it doesn't clash with the picks, is that okay @ramonh? great work :+1:

**Comment by ramonh** [comment]
Sounds great, thank you @alicetragedy! Glad it works

**Comment by pferdefleisch** [comment]
Yeah, this is great. Thanks @ramonh

**Comment by ramonh** [comment]
No probs! I'm glad the both of you like it. I'll continue to do these for the upcoming meetups and have them up in a hopefully more timely fashion

**Pull request merged**
